version: "2.0"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    container_name: pagermaid
    hostname: pagermaid
    #ports:                 # 是否开启网页控制面板
      #- "3333:3333"
    volumes:
      - ./:/pagermaid/workdir
    environment:
      - RUN_AS_ROOT=true    # 是否以root权限运行pagermaid，true为是
      - PUID=917            # 当 RUN_AS_ROOT=false 才生效，即以普通用户权限运行pagermaid
      - PGID=917            # 当 RUN_AS_ROOT=false 才生效，即以普通用户权限运行pagermaid
