version: '3.8'

services:
  alert_bot:
    # build: .
    image: keyword_alert_bot:dev
    volumes:
      - ./../config.yml:/app/config.yml
    restart: always
    networks:
      - internal
networks:
  internal:
