version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: ./script/build.sh latest
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Deploy
          command: curl -X POST -d '{"from":"circleci2"}' "$DOCKER_REBUILD_URL"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master